language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - cp /c/Python38/python.exe /c/Python38/python3.exe
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_SKIP="cp27-* cp33-*"
    - CIBW_BEFORE_BUILD="python -m pip install cython numpy"
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings

install:
  - python3 -m pip install twine cibuildwheel==1.5.4

script:
  # build the wheels, put them into './wheelhouse'
  - if [[ $TRAVIS_TAG ]]; then python3 -m cibuildwheel --output-dir wheelhouse; fi

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python3 -m twine upload wheelhouse/*.whl; fi